# Generated by Django 4.2.3 on 2023-08-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
    ]
