# Generated by Django 4.2.3 on 2023-08-04 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
