# Generated by Django 4.2.3 on 2023-08-05 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='problems',
            name='data_type',
            field=models.CharField(blank=True, choices=[('int', 'Int'), ('str', 'Str'), ('list', 'List'), ('bool', 'Bool'), ('float', 'Float'), ('dict', 'Dict'), ('set', 'Set')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='input',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
