# Generated by Django 4.2.2 on 2023-07-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.problems'),
        ),
    ]
