# Generated by Django 4.2.2 on 2023-07-20 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_example_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputexample',
            name='example',
        ),
        migrations.AddField(
            model_name='problems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='input',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='output',
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='InputExample',
        ),
    ]
