# Generated by Django 4.2.3 on 2023-07-17 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_answer_runtime_remove_problems_acceptance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='target',
        ),
        migrations.AddField(
            model_name='example',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InputExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=255)),
                ('variable_value', models.CharField(max_length=255)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.example')),
            ],
        ),
    ]
