# Generated by Django 4.2.3 on 2023-07-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_example_target_example_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='input',
        ),
    ]
